import { DifficultyLevel } from './word';

export type StoryFormat = 'prose' | 'dialog';

/** Gender of a dialog character, reported by the AI at generation time. */
export type SpeakerGender = 'male' | 'female';

/** One character of a dialog story, as generated by the AI. */
export interface StorySpeaker {
  /** The exact name used as the script line prefix (e.g. "Anna"). */
  name: string;
  gender: SpeakerGender;
}

export interface Story {
  id: string;
  title: string;
  german: string;
  /** English translation. Generated on demand — empty until the user asks. */
  translationEn?: string;
  /** Russian translation. Generated on demand — empty until the user asks. */
  translationRu?: string;
  level: DifficultyLevel;
  domain: string;
  grammarTopics: string[];
  wordCount: number;
  createdAt: string;
  audioUrl?: string;
  /** 'dialog' = the German text is a scripted conversation (one line per speaker). */
  format?: StoryFormat;
  /**
   * Characters of a dialog story with the genders the AI chose for them.
   * Used to pair Fish Audio voices correctly (male/female) at playback.
   */
  speakers?: StorySpeaker[];
}

export interface StoryConfig {
  theme: string;
  level: DifficultyLevel;
  wordTypes: string[];
  grammarTopics: string[];
  sentenceCount: number;
  format?: StoryFormat;
}